cobbler: Allow ifdown to fail during rc.local
Behavior changed in RHEL8.  See example below.

```
+ ifdown enp3s0f1
Error: '/etc/sysconfig/network-scripts/ifcfg-enp3s0f1' is not an active connection.
Error: no active connection provided.
```

Then the script would quit.

Signed-off-by: David Galloway <dgallowa@redhat.com>